### ISSUE TITLE
Entrées / Sorties

### ISSUE THREAD

**Issue by Juliebiro** [N445/erepublik#3]
Nous avons oublié un joueur dans le SMA (soit gibus, soit moi): Mulltany 4953808
J'ai vérifié ses kills pour cette semaine et j'ai versé la prime
J'ouvre ici pour qu'il soit dans le xls de la semaine prochaine

Quatre joueurs sont "dead citizen" et quittent le SMA: overpol81, ShivaGanesha, LepusArticus et Mordgrim
D'ores et déjà je ne les ai pas mis dans l'article de cette semaine (reco de gibus)
Pour info, le compte acquiert le statut dead citizen après 30 jours d'inactivité totale, toutefois tout est conservé sur le server, visiblement aucun compte n'est jamais supprimé par les admins

**Comment by N445** [comment]
Je vais voir si je peux automatisé ça. De mémoire j'ai accès a cette données pendant l’exécution du script
