### ISSUE TITLE
Entrée

### ISSUE THREAD

**Issue by Juliebiro** [N445/erepublik#9]
Keyloraz
erepublik.com/en/citizen/profile/8450879

**Comment by N445** [comment]
Déjà fais désolé j’avais oublié de prévenir

**Comment by Juliebiro** [comment]
je m'en doutais mais je me suis dit qu'en postant sur github on garde une
trace de tout ce qu'on fait


Le dim. 5 janv. 2020 à 12:44, Robin Parisot <notifications@github.com> a
écrit :
